#application: project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

libraries:
- name: PIL
  version: latest
inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/admin
  static_dir: django/contrib/admin/static/admin
  expiration: '0'

- url: /static/rest_framework
  static_dir: rest_framework/static/rest_framework
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application

skip_files:
  submodules

